- name: Edit /opt/mattermost/config/config.json
  replace:
    path: /opt/mattermost/config/config.json
    regexp: '.*"ConnectionSecurity": "",$'
    replace: '\t"ConnectionSecurity": "TLS",'
    before: '.*"TLSCertFile".*'

- name: Edit /opt/mattermost/config/config.json
  lineinfile:
    dest: /opt/mattermost/config/config.json
    regexp: '"TLSCertFile":'
    line: '\t"TLSCertFile": "/etc/pki/tls/certs/{{ ansible_fqdn }}.pem",'
    backrefs: yes

- name: Edit /opt/mattermost/config/config.json
  lineinfile:
    dest: /opt/mattermost/config/config.json
    regexp: '"TLSKeyFile":'
    line: '\t"TLSKeyFile": "/etc/pki/tls/private/{{ ansible_fqdn }}.pem",'
    backrefs: yes

- name: Edit /opt/mattermost/config/config.json
  lineinfile:
    dest: /opt/mattermost/config/config.json
    regexp: '"ListenAddress": ":8065",'
    line: '\t"ListenAddress": ":{{ mattermost_tls_port }}",'
    backrefs: yes

- name: Edit /opt/mattermost/config/config.json
  lineinfile:
    dest: /opt/mattermost/config/config.json
    regexp: '"Forward80To443": false,'
    line: '\t"Forward80To443": true,'
    backrefs: yes

- name: Upload certificate
  copy:
    src: "{{ mattermost_certificate_file }}"
    dest: "/etc/pki/tls/certs/{{ ansible_fqdn }}.pem"
    mode: 0740
    owner: "{{ mattermost_user }}"
    group: "{{ mattermost_user }}"

- name: Upload private key
  copy:
    src: "{{ mattermost_private_key_file }}"
    dest: "/etc/pki/tls/private/{{ ansible_fqdn }}.pem"
    mode: 0700
    owner: "{{ mattermost_user }}"
    group: "{{ mattermost_user }}"

- name: Set net bind capability
  capabilities:
    path: /opt/mattermost/bin/mattermost
    capability: cap_net_bind_service+ep
    state: present
